### ISSUE TITLE
[Afterwork] Develop "Basic" features

### ISSUE THREAD

**Issue by nicobao** [zkorum/agora#73]
Associated design: https://github.com/zkorum/zkorum/issues/75

Order of implementation may or may not matter (if nothing is written, then order doesn't matter).

- [ ] https://github.com/zkorum/zkorum/issues/63 => make sure to do this first to use i18n variables from the start
- [ ] https://github.com/zkorum/zkorum/issues/60 => @nicobao only => should be done 2nd
- [ ] https://github.com/zkorum/zkorum/issues/61 => @nicobao should be done 3rd
- [x] https://github.com/zkorum/zkorum/issues/62
- [x] https://github.com/zkorum/zkorum/issues/64
- [x] https://github.com/zkorum/zkorum/issues/65
- [x] https://github.com/zkorum/zkorum/issues/66
- [x] https://github.com/zkorum/zkorum/issues/67
- [x] https://github.com/zkorum/zkorum/issues/68
- [x] https://github.com/zkorum/zkorum/issues/69
- [x] https://github.com/zkorum/zkorum/issues/70
- [x] https://github.com/zkorum/zkorum/issues/71
- [x] https://github.com/zkorum/zkorum/issues/72
- [x] https://github.com/zkorum/zkorum/issues/74
